/**
 * Routes for Contest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { cancelContest, createContest, getContest, listContests, updateContest } from "../handlers/contest.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function contestRoutes(fastify: FastifyInstance) {
  // POST /v1/contests (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/contests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContestsDependenciesForRequest();
        await createContest(request, reply, deps);
      });
    }
  );


  // GET /v1/contests (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContestsDependenciesForRequest();
        await listContests(request, reply, deps);
      });
    }
  );


  // DELETE /v1/contests/{contestId} (unscoped; scope set for security middleware)
  fastify.delete(
    "/v1/contests/:contestId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContestsDependenciesForRequest();
        await cancelContest(request, reply, deps);
      });
    }
  );


  // GET /v1/contests/{contestId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contests/:contestId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContestsDependenciesForRequest();
        await getContest(request, reply, deps);
      });
    }
  );


  // PATCH /v1/contests/{contestId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/contests/:contestId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContestsDependenciesForRequest();
        await updateContest(request, reply, deps);
      });
    }
  );


}
