/**
 * Contests DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Contests Domain Module - Composition root
 *
 * DDD: Composition root for contests domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ContestRepositoryAdapter,
  ExportRepositoryAdapter,
} from "@modelescrow/adapters/contests";
import { getIdGeneratorService } from "@modelescrow/adapters";
import type { AdapterDynamoDBClient } from "@modelescrow/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCancelContest,
  ExecuteCreateContest,
  ExecuteGetContest,
  ExecuteListContests,
  ExecuteUpdateContest,
} from "@modelescrow/services/contests/usecases";
// Ports (interfaces)
import type {
  ContestRepository,
  ExportRepository,
} from "@modelescrow/services/contests/ports";

export interface ContestsDomainModule {
  repos: {
    contests: ContestRepository;
    exports: ExportRepository;
  };
  useCases: {
    contests: {
      create: ExecuteCreateContest;
      get: ExecuteGetContest;
      list: ExecuteListContests;
      update: ExecuteCancelContest;
    };
  };
}

export function buildContestsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ContestsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      contests?: ContestRepository;
      exports?: ExportRepository;
    } = {};

    obj.contests = new ContestRepositoryAdapter(dynamoClient);
    obj.exports = new ExportRepositoryAdapter(dynamoClient);
    return {
      contests: obj.contests!,
      exports: obj.exports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    contests: {
      create: new ExecuteCreateContest(executionContext, idGenerator, repos.contests),
      get: new ExecuteGetContest(executionContext, idGenerator, repos.contests),
      list: new ExecuteListContests(executionContext, idGenerator, repos.contests),
      update: new ExecuteCancelContest(executionContext, idGenerator, repos.contests),
    },
  };
  return { repos, useCases: useCases as ContestsDomainModule["useCases"] };
}
