/**
 * Submissions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Submissions Domain Module - Composition root
 *
 * DDD: Composition root for submissions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  SubmissionRepositoryAdapter,
} from "@modelescrow/adapters/submissions";
import { getIdGeneratorService } from "@modelescrow/adapters";
import type { AdapterDynamoDBClient } from "@modelescrow/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetSubmission,
  ExecuteListSubmissions,
  ExecuteSubmitModel,
  ExecuteWithdrawSubmission,
} from "@modelescrow/services/submissions/usecases";
// Ports (interfaces)
import type {
  SubmissionRepository,
} from "@modelescrow/services/submissions/ports";

export interface SubmissionsDomainModule {
  repos: {
    submissions: SubmissionRepository;
  };
  useCases: {
    submissions: {
      create: ExecuteSubmitModel;
      get: ExecuteWithdrawSubmission;
      list: ExecuteListSubmissions;
    };
  };
}

export function buildSubmissionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SubmissionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      submissions?: SubmissionRepository;
    } = {};

    obj.submissions = new SubmissionRepositoryAdapter(dynamoClient);
    return {
      submissions: obj.submissions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    submissions: {
      create: new ExecuteSubmitModel(executionContext, idGenerator, repos.submissions),
      get: new ExecuteWithdrawSubmission(executionContext, idGenerator, repos.submissions),
      list: new ExecuteListSubmissions(executionContext, idGenerator, repos.submissions),
    },
  };
  return { repos, useCases: useCases as SubmissionsDomainModule["useCases"] };
}
