/**
 * Repository interface for DeployGate
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DeployGateEntity
} from "../models/deploy-gate.entity.js";
import type {
  ListDeployGatesParams,
  DeployGate
} from "../types/index.js";
/**
 * DeployGateRepository Interface
 */
export interface DeployGateRepository extends CreateReadRepository<DeployGateEntity, DeployGate, string, ListDeployGatesParams> {

}
