/**
 * DeployGate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/deploygates.openapi.types.js";
import { schemas } from "../schemas/deploygates.schemas.js";

/**
 * Entity: DeployGateEntity
 * Description: Represents the DeployGate domain model.
 * Source: schemas.DeployGate
 * Type: Domain Entity (API)
 */
export const DeployGateEntitySchema = schemas.DeployGate;
export type DeployGateEntity = components["schemas"]["DeployGate"];
