/**
 * Repository interface for Submission
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateDeleteReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SubmissionEntity
} from "../models/submission.entity.js";
import type {
  ListSubmissionsParams,
  Submission
} from "../types/index.js";
/**
 * SubmissionRepository Interface
 */
export interface SubmissionRepository extends CreateDeleteReadRepository<SubmissionEntity, Submission, string, ListSubmissionsParams> {

}
