/**
 * Repository interface for Escrow
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: escrows
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EscrowEntity
} from "../models/escrow.entity.js";
import type {
  Escrow
} from "../types/index.js";
/**
 * EscrowRepository Interface
 */
export interface EscrowRepository extends CreateReadRepository<EscrowEntity, Escrow, string, Record<string, never>> {

}
