/**
 * ExecuteListEvaluationsForSubmission - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEvaluationsForSubmission Use Case
 *
 * DDD: Application use case for list Evaluation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEvaluationsForSubmissionInput, ListEvaluationsForSubmissionOutput } from "../dto/evaluation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { EvaluationRepository } from "../ports";

export class ExecuteListEvaluationsForSubmission {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evaluation: EvaluationRepository
  ) {}

  async execute(input: ListEvaluationsForSubmissionInput): Promise<ListEvaluationsForSubmissionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.evaluation.listEvaluationsForSubmission({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEvaluationsForSubmissionOutput;
  }
}
