/**
 * DeployGateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeployGateRepository Port
 *
 * DDD: Application port for deploygaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDeployGateInput, CreateDeployGateOutput, DecideDeployGateInput, DecideDeployGateOutput, GetDeployGateInput, GetDeployGateOutput, ListDeployGatesInput, ListDeployGatesOutput } from "../dto/deploy-gate.dto";
export interface DeployGateRepository {
  listDeployGates(input: ListDeployGatesInput): Promise<ListDeployGatesOutput>;
  createDeployGate(input: CreateDeployGateInput): Promise<CreateDeployGateOutput>;
  getDeployGate(input: GetDeployGateInput): Promise<GetDeployGateOutput>;
  decideDeployGate(input: DecideDeployGateInput): Promise<DecideDeployGateOutput>;
}

export type { CreateDeployGateInput, CreateDeployGateOutput, DecideDeployGateInput, DecideDeployGateOutput, GetDeployGateInput, GetDeployGateOutput, ListDeployGatesInput, ListDeployGatesOutput } from "../dto/deploy-gate.dto";
