/**
 * EscrowRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escrows
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EscrowRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EscrowRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EscrowRepository,
} from "@modelescrow/services/escrows";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EscrowRepositoryDdb } from "./escrow-repository.ddb.js";

/**
 * EscrowRepositoryAdapter
 *
 * Implements EscrowRepository port for infrastructure layer.
 */
export class EscrowRepositoryAdapter implements EscrowRepository {
  private readonly ddb: EscrowRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EscrowRepositoryDdb(this.dynamoClient);
  }

  async getEscrow(input: Parameters<EscrowRepository['getEscrow']>[0]): Promise<Awaited<ReturnType<EscrowRepository['getEscrow']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEscrow(input);
  }

  async lockEscrow(input: Parameters<EscrowRepository['lockEscrow']>[0]): Promise<Awaited<ReturnType<EscrowRepository['lockEscrow']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.lockEscrow(input);
  }

  async getEscrowById(input: Parameters<EscrowRepository['getEscrowById']>[0]): Promise<Awaited<ReturnType<EscrowRepository['getEscrowById']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEscrowById(input);
  }
}
