/**
 * ContestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContestRepository Port
 *
 * DDD: Application port for contestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CancelContestInput, CancelContestOutput, CreateContestInput, CreateContestOutput, GetContestInput, GetContestOutput, ListContestsInput, ListContestsOutput, UpdateContestInput, UpdateContestOutput } from "../dto/contest.dto";
export interface ContestRepository {
  listContests(input: ListContestsInput): Promise<ListContestsOutput>;
  createContest(input: CreateContestInput): Promise<CreateContestOutput>;
  getContest(input: GetContestInput): Promise<GetContestOutput>;
  updateContest(input: UpdateContestInput): Promise<UpdateContestOutput>;
  cancelContest(input: CancelContestInput): Promise<CancelContestOutput>;
}

export type { CancelContestInput, CancelContestOutput, CreateContestInput, CreateContestOutput, GetContestInput, GetContestOutput, ListContestsInput, ListContestsOutput, UpdateContestInput, UpdateContestOutput } from "../dto/contest.dto";
