/**
 * ExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportRepository Port
 *
 * DDD: Application port for exportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAuditExportInput, CreateAuditExportOutput } from "../dto/export.dto";
export interface ExportRepository {
  createAuditExport(input: CreateAuditExportInput): Promise<CreateAuditExportOutput>;
}

export type { CreateAuditExportInput, CreateAuditExportOutput } from "../dto/export.dto";
