/**
 * Handlers for Contest
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ContestsDomainModule } from "../dependencies/contests-ddd.dependencies.js";
import type { CancelContestInput, CreateContestInput, GetContestInput, ListContestsInput, UpdateContestInput } from "@modelescrow/services/contests";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/contests
 * Operation: listContests
 */
export async function listContests(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ContestsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListContestsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.contests.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/contests
 * Operation: createContest
 */
export async function createContest(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ContestsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateContestInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.contests.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/contests/{contestId}
 * Operation: getContest
 */
export async function getContest(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ContestsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetContestInput = {
    contestId: request.params.contestId,
  };
  const result = await deps.useCases.contests.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/contests/{contestId}
 * Operation: updateContest
 */
export async function updateContest(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ContestsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateContestInput = {
    contestId: request.params.contestId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.contests.update.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for DELETE /v1/contests/{contestId}
 * Operation: cancelContest
 */
export async function cancelContest(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ContestsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CancelContestInput = {
    contestId: request.params.contestId,
  };
  const result = await deps.useCases.contests.update.execute(input);
  return reply.code(204).send(result);
}


