/**
 * DisputeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisputeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DisputeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DisputeRepository,
} from "@modelescrow/services/disputes";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DisputeRepositoryDdb } from "./dispute-repository.ddb.js";

/**
 * DisputeRepositoryAdapter
 *
 * Implements DisputeRepository port for infrastructure layer.
 */
export class DisputeRepositoryAdapter implements DisputeRepository {
  private readonly ddb: DisputeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DisputeRepositoryDdb(this.dynamoClient);
  }

  async listDisputes(input: Parameters<DisputeRepository['listDisputes']>[0]): Promise<Awaited<ReturnType<DisputeRepository['listDisputes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDisputes(input);
  }

  async openEvaluationDispute(input: Parameters<DisputeRepository['openEvaluationDispute']>[0]): Promise<Awaited<ReturnType<DisputeRepository['openEvaluationDispute']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openEvaluationDispute(input);
  }

  async getDispute(input: Parameters<DisputeRepository['getDispute']>[0]): Promise<Awaited<ReturnType<DisputeRepository['getDispute']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDispute(input);
  }

  async resolveDispute(input: Parameters<DisputeRepository['resolveDispute']>[0]): Promise<Awaited<ReturnType<DisputeRepository['resolveDispute']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.resolveDispute(input);
  }
}
