/**
 * ExecuteGetSubmission - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSubmission Use Case
 *
 * DDD: Application use case for get Submission.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSubmissionInput, GetSubmissionOutput } from "../dto/submission.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { SubmissionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetSubmission {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly submission: SubmissionRepository
  ) {}

  async execute(input: GetSubmissionInput): Promise<GetSubmissionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.subId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).submissionId) {
      throw new ValidationError("submissionId is required");
    }
    const submissionId = (input as any).submissionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.submission.getSubmission({ submissionId: submissionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${submissionId}`);
    }

    return entity as GetSubmissionOutput;
  }
}
