/**
 * Evaluations Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/contests/:contestId/leaderboard',
    alias: 'getLeaderboard',
    requestFormat: 'json',
    parameters: [
      {
        name: 'contestId',
        type: 'Path',
        schema: z.string(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            contestId: z.string(),
            entries: z.array(
              z
                .object({
                  submissionId: z.string(),
                  providerId: z.string(),
                  score: z.number(),
                  rank: z.number().int(),
                  evaluationRunId: z.string().optional(),
                })
                .passthrough()
            ),
            visibility: z.enum(['public', 'private']).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/evaluations/:evaluationRunId',
    alias: 'getEvaluationRun',
    requestFormat: 'json',
    parameters: [
      {
        name: 'evaluationRunId',
        type: 'Path',
        schema: z.string().regex(/^evr_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            evaluationRunId: z.string().regex(/^evr_[0-9A-HJKMNP-TV-Z]{26}$/),
            submissionId: z.string(),
            contestId: z.string(),
            status: z.enum([
              'queued',
              'running',
              'completed',
              'failed',
              'invalidated',
            ]),
            score: z.number().optional(),
            metricName: z.string(),
            environmentHash: z.string().optional(),
            logHash: z.string().optional(),
            logExcerpt: z.string().optional(),
            invalidationReason: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/evaluations/:evaluationRunId/invalidate',
    alias: 'invalidateEvaluationRun',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: z.object({ reason: z.string().min(1) }).passthrough(),
      },
      {
        name: 'evaluationRunId',
        type: 'Path',
        schema: z.string().regex(/^evr_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            evaluationRunId: z.string().regex(/^evr_[0-9A-HJKMNP-TV-Z]{26}$/),
            submissionId: z.string(),
            contestId: z.string(),
            status: z.enum([
              'queued',
              'running',
              'completed',
              'failed',
              'invalidated',
            ]),
            score: z.number().optional(),
            metricName: z.string(),
            environmentHash: z.string().optional(),
            logHash: z.string().optional(),
            logExcerpt: z.string().optional(),
            invalidationReason: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/submissions/:submissionId/evaluations',
    alias: 'listEvaluationsForSubmission',
    requestFormat: 'json',
    parameters: [
      {
        name: 'submissionId',
        type: 'Path',
        schema: z.string(),
      },
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  evaluationRunId: z
                    .string()
                    .regex(/^evr_[0-9A-HJKMNP-TV-Z]{26}$/),
                  submissionId: z.string(),
                  contestId: z.string(),
                  status: z.enum([
                    'queued',
                    'running',
                    'completed',
                    'failed',
                    'invalidated',
                  ]),
                  score: z.number().optional(),
                  metricName: z.string(),
                  environmentHash: z.string().optional(),
                  logHash: z.string().optional(),
                  logExcerpt: z.string().optional(),
                  invalidationReason: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/submissions/:submissionId/evaluations',
    alias: 'runEvaluation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'submissionId',
        type: 'Path',
        schema: z.string(),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            evaluationRunId: z.string().regex(/^evr_[0-9A-HJKMNP-TV-Z]{26}$/),
            submissionId: z.string(),
            contestId: z.string(),
            status: z.enum([
              'queued',
              'running',
              'completed',
              'failed',
              'invalidated',
            ]),
            score: z.number().optional(),
            metricName: z.string(),
            environmentHash: z.string().optional(),
            logHash: z.string().optional(),
            logExcerpt: z.string().optional(),
            invalidationReason: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
