/**
 * DeployGateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeployGateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DeployGateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DeployGateRepository,
} from "@modelescrow/services/deploygates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DeployGateRepositoryDdb } from "./deploy-gate-repository.ddb.js";

/**
 * DeployGateRepositoryAdapter
 *
 * Implements DeployGateRepository port for infrastructure layer.
 */
export class DeployGateRepositoryAdapter implements DeployGateRepository {
  private readonly ddb: DeployGateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DeployGateRepositoryDdb(this.dynamoClient);
  }

  async listDeployGates(input: Parameters<DeployGateRepository['listDeployGates']>[0]): Promise<Awaited<ReturnType<DeployGateRepository['listDeployGates']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDeployGates(input);
  }

  async createDeployGate(input: Parameters<DeployGateRepository['createDeployGate']>[0]): Promise<Awaited<ReturnType<DeployGateRepository['createDeployGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDeployGate(input);
  }

  async getDeployGate(input: Parameters<DeployGateRepository['getDeployGate']>[0]): Promise<Awaited<ReturnType<DeployGateRepository['getDeployGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDeployGate(input);
  }

  async decideDeployGate(input: Parameters<DeployGateRepository['decideDeployGate']>[0]): Promise<Awaited<ReturnType<DeployGateRepository['decideDeployGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.decideDeployGate(input);
  }
}
