/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @modelescrow/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@modelescrow/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@modelescrow/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@modelescrow/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@modelescrow/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@modelescrow/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _contests from "./contests/index.js";
import * as _deploygates from "./deploygates/index.js";
import * as _disputes from "./disputes/index.js";
import * as _escrows from "./escrows/index.js";
import * as _evaluations from "./evaluations/index.js";
import * as _identity from "./identity/index.js";
import * as _settlements from "./settlements/index.js";
import * as _submissions from "./submissions/index.js";

// Export as namespaces
export const _shared = __shared;
export const contests = _contests;
export const deploygates = _deploygates;
export const disputes = _disputes;
export const escrows = _escrows;
export const evaluations = _evaluations;
export const identity = _identity;
export const settlements = _settlements;
export const submissions = _submissions;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@modelescrow/core"; activity.types.*
//   - Direct exports: import * from "@modelescrow/core/activity/types/index.js"
//   - Direct exports: import * from "@modelescrow/core/activity/repositories/index.js"
//   - Direct exports: import * from "@modelescrow/core/activity/models/index.js"
//   - Direct exports: import * from "@modelescrow/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Contests Service
export { schemas as ContestsSchemas } from "./contests/schemas/contests.schemas.js";

// Deploygates Service
export { schemas as DeploygatesSchemas } from "./deploygates/schemas/deploygates.schemas.js";

// Disputes Service
export { schemas as DisputesSchemas } from "./disputes/schemas/disputes.schemas.js";

// Escrows Service
export { schemas as EscrowsSchemas } from "./escrows/schemas/escrows.schemas.js";

// Evaluations Service
export { schemas as EvaluationsSchemas } from "./evaluations/schemas/evaluations.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Settlements Service
export { schemas as SettlementsSchemas } from "./settlements/schemas/settlements.schemas.js";

// Submissions Service
export { schemas as SubmissionsSchemas } from "./submissions/schemas/submissions.schemas.js";

