/**
 * Contest Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/contests.openapi.types.js";
import { schemas } from "../schemas/contests.schemas.js";

/**
 * Entity: ContestEntity
 * Description: Represents the Contest domain model.
 * Source: schemas.Contest
 * Type: Domain Entity (API)
 */
export const ContestEntitySchema = schemas.Contest;
export type ContestEntity = components["schemas"]["Contest"];
