/**
 * Submission DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Submission DTOs
 *
 * DDD: Application DTOs for Submission use cases.
 */

import type { GetSubmissionParams, ListSubmissionsParams, SubmitModelParams, SubmitModelRequestInput, WithdrawSubmissionParams } from "@modelescrow/core/submissions/types";

export type ListSubmissionsInput = ListSubmissionsParams;

export type SubmitModelInput = SubmitModelParams & SubmitModelRequestInput;

export type GetSubmissionInput = GetSubmissionParams;

export type WithdrawSubmissionInput = WithdrawSubmissionParams;

export type ListSubmissionsOutput = {};

export type SubmitModelOutput = {};

export type GetSubmissionOutput = {};

export type WithdrawSubmissionOutput = {};
