/**
 * Handlers for Escrow
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escrows
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EscrowsDomainModule } from "../dependencies/escrows-ddd.dependencies.js";
import type { GetEscrowByIdInput, GetEscrowInput, LockEscrowInput } from "@modelescrow/services/escrows";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/contests/{contestId}/escrow
 * Operation: getEscrow
 */
export async function getEscrow(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EscrowsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEscrowInput = {
    contestId: request.params.contestId,
  };
  const result = await deps.useCases.escrows.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/contests/{contestId}/escrow
 * Operation: lockEscrow
 */
export async function lockEscrow(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EscrowsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: LockEscrowInput = {
    contestId: request.params.contestId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.escrows.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/escrows/{escrowId}
 * Operation: getEscrowById
 */
export async function getEscrowById(
  request: FastifyRequest<{ Params: { escrowId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EscrowsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEscrowByIdInput = {
    escrowId: request.params.escrowId,
  };
  const result = await deps.useCases.escrows.getById.execute(input);
  return reply.code(200).send(result);
}


