/**
 * Routes for Submission
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getSubmission, listSubmissions, submitModel, withdrawSubmission } from "../handlers/submission.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function submissionRoutes(fastify: FastifyInstance) {
  // GET /v1/contests/{contestId}/submissions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contests/:contestId/submissions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubmissionsDependenciesForRequest();
        await listSubmissions(request, reply, deps);
      });
    }
  );


  // POST /v1/contests/{contestId}/submissions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/contests/:contestId/submissions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubmissionsDependenciesForRequest();
        await submitModel(request, reply, deps);
      });
    }
  );


  // GET /v1/submissions/{submissionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/submissions/:submissionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { submissionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubmissionsDependenciesForRequest();
        await getSubmission(request, reply, deps);
      });
    }
  );


  // DELETE /v1/submissions/{submissionId} (unscoped; scope set for security middleware)
  fastify.delete(
    "/v1/submissions/:submissionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { submissionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubmissionsDependenciesForRequest();
        await withdrawSubmission(request, reply, deps);
      });
    }
  );


}
