/**
 * Evaluations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Evaluations Domain Module - Composition root
 *
 * DDD: Composition root for evaluations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EvaluationRepositoryAdapter,
  InvalidateRepositoryAdapter,
  LeaderboardRepositoryAdapter,
} from "@modelescrow/adapters/evaluations";
import { getIdGeneratorService } from "@modelescrow/adapters";
import type { AdapterDynamoDBClient } from "@modelescrow/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetEvaluationRun,
  ExecuteInvalidateEvaluationRun,
  ExecuteListEvaluationsForSubmission,
  ExecuteRunEvaluation,
} from "@modelescrow/services/evaluations/usecases";
// Ports (interfaces)
import type {
  EvaluationRepository,
  InvalidateRepository,
  LeaderboardRepository,
} from "@modelescrow/services/evaluations/ports";

export interface EvaluationsDomainModule {
  repos: {
    evaluations: EvaluationRepository;
    invalidates: InvalidateRepository;
    leaderboards: LeaderboardRepository;
  };
  useCases: {
    evaluations: {
      create: ExecuteRunEvaluation;
      get: ExecuteGetEvaluationRun;
      list: ExecuteListEvaluationsForSubmission;
    };
    invalidates: {
      get: ExecuteInvalidateEvaluationRun;
    };
  };
}

export function buildEvaluationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EvaluationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      evaluations?: EvaluationRepository;
      invalidates?: InvalidateRepository;
      leaderboards?: LeaderboardRepository;
    } = {};

    obj.evaluations = new EvaluationRepositoryAdapter(dynamoClient);
    obj.invalidates = new InvalidateRepositoryAdapter(dynamoClient);
    obj.leaderboards = new LeaderboardRepositoryAdapter(dynamoClient);
    return {
      evaluations: obj.evaluations!,
      invalidates: obj.invalidates!,
      leaderboards: obj.leaderboards!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    evaluations: {
      create: new ExecuteRunEvaluation(executionContext, idGenerator, repos.evaluations),
      get: new ExecuteGetEvaluationRun(executionContext, idGenerator, repos.evaluations),
      list: new ExecuteListEvaluationsForSubmission(executionContext, idGenerator, repos.evaluations),
    },
    invalidates: {
      get: new ExecuteInvalidateEvaluationRun(executionContext, idGenerator, repos.invalidates),
    },
  };
  return { repos, useCases: useCases as EvaluationsDomainModule["useCases"] };
}
