/**
 * Routes for DeployGate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDeployGate, decideDeployGate, getDeployGate, listDeployGates } from "../handlers/deploy-gate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function deployGateRoutes(fastify: FastifyInstance) {
  // POST /v1/contests/{contestId}/deploy-gates (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/contests/:contestId/deploy-gates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeploygatesDependenciesForRequest();
        await createDeployGate(request, reply, deps);
      });
    }
  );


  // GET /v1/contests/{contestId}/deploy-gates (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contests/:contestId/deploy-gates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeploygatesDependenciesForRequest();
        await listDeployGates(request, reply, deps);
      });
    }
  );


  // POST /v1/deploy-gates/{deployGateId} (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/deploy-gates/:deployGateId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { deployGateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeploygatesDependenciesForRequest();
        await decideDeployGate(request, reply, deps);
      });
    }
  );


  // GET /v1/deploy-gates/{deployGateId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/deploy-gates/:deployGateId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { deployGateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeploygatesDependenciesForRequest();
        await getDeployGate(request, reply, deps);
      });
    }
  );


}
