/**
 * Deploygates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Deploygates Domain Module - Composition root
 *
 * DDD: Composition root for deploygates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DeployGateRepositoryAdapter,
} from "@modelescrow/adapters/deploygates";
import { getIdGeneratorService } from "@modelescrow/adapters";
import type { AdapterDynamoDBClient } from "@modelescrow/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDeployGate,
  ExecuteDecideDeployGate,
  ExecuteGetDeployGate,
  ExecuteListDeployGates,
} from "@modelescrow/services/deploygates/usecases";
// Ports (interfaces)
import type {
  DeployGateRepository,
} from "@modelescrow/services/deploygates/ports";

export interface DeploygatesDomainModule {
  repos: {
    deployGates: DeployGateRepository;
  };
  useCases: {
    deployGates: {
      create: ExecuteCreateDeployGate;
      get: ExecuteDecideDeployGate;
      list: ExecuteListDeployGates;
    };
  };
}

export function buildDeploygatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DeploygatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      deployGates?: DeployGateRepository;
    } = {};

    obj.deployGates = new DeployGateRepositoryAdapter(dynamoClient);
    return {
      deployGates: obj.deployGates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    deployGates: {
      create: new ExecuteCreateDeployGate(executionContext, idGenerator, repos.deployGates),
      get: new ExecuteDecideDeployGate(executionContext, idGenerator, repos.deployGates),
      list: new ExecuteListDeployGates(executionContext, idGenerator, repos.deployGates),
    },
  };
  return { repos, useCases: useCases as DeploygatesDomainModule["useCases"] };
}
