/**
 * ExecuteGetDeployGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDeployGate Use Case
 *
 * DDD: Application use case for get DeployGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDeployGateInput, GetDeployGateOutput } from "../dto/deploy-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { DeployGateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDeployGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deployGate: DeployGateRepository
  ) {}

  async execute(input: GetDeployGateInput): Promise<GetDeployGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dgtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).deployGateId) {
      throw new ValidationError("deployGateId is required");
    }
    const deploygateId = (input as any).deployGateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.deployGate.getDeployGate({ deployGateId: deploygateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${deploygateId}`);
    }

    return entity as GetDeployGateOutput;
  }
}
