/**
 * ExecuteListDeployGates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDeployGates Use Case
 *
 * DDD: Application use case for list DeployGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDeployGatesInput, ListDeployGatesOutput } from "../dto/deploy-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { DeployGateRepository } from "../ports";

export class ExecuteListDeployGates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deployGate: DeployGateRepository
  ) {}

  async execute(input: ListDeployGatesInput): Promise<ListDeployGatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dgtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.deployGate.listDeployGates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDeployGatesOutput;
  }
}
