/**
 * ExecuteCreateDeployGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDeployGate Use Case
 *
 * DDD: Application use case for create DeployGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDeployGateInput, CreateDeployGateOutput } from "../dto/deploy-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { DeployGateRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDeployGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deployGate: DeployGateRepository
  ) {}

  async execute(input: CreateDeployGateInput): Promise<CreateDeployGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dgtId();

    // All field names extracted from OpenAPI spec: registryWebhookUri, submissionId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.submissionId) {
      throw new ValidationError("submissionId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (deploygates domain)
    const entityId = this.idGenerator.dgtId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.deployGate.createDeployGate({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDeployGateOutput;
  }
}
