/**
 * EscrowRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escrows
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EscrowRepository Port
 *
 * DDD: Application port for escrowrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEscrowByIdInput, GetEscrowByIdOutput, GetEscrowInput, GetEscrowOutput, LockEscrowInput, LockEscrowOutput } from "../dto/escrow.dto";
export interface EscrowRepository {
  getEscrow(input: GetEscrowInput): Promise<GetEscrowOutput>;
  lockEscrow(input: LockEscrowInput): Promise<LockEscrowOutput>;
  getEscrowById(input: GetEscrowByIdInput): Promise<GetEscrowByIdOutput>;
}

export type { GetEscrowByIdInput, GetEscrowByIdOutput, GetEscrowInput, GetEscrowOutput, LockEscrowInput, LockEscrowOutput } from "../dto/escrow.dto";
