/**
 * Contest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Contest DTOs
 *
 * DDD: Application DTOs for Contest use cases.
 */

import type { CancelContestParams, CreateContestRequestInput, GetContestParams, ListContestsParams, UpdateContestParams, UpdateContestRequestInput } from "@modelescrow/core/contests/types";

export type ListContestsInput = ListContestsParams;

export type CreateContestInput = CreateContestRequestInput;

export type GetContestInput = GetContestParams;

export type UpdateContestInput = UpdateContestParams & UpdateContestRequestInput;

export type CancelContestInput = CancelContestParams;

export type ListContestsOutput = {};

export type CreateContestOutput = {};

export type GetContestOutput = {};

export type UpdateContestOutput = {};

export type CancelContestOutput = {};
