/**
 * Handlers for Settlement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SettlementsDomainModule } from "../dependencies/settlements-ddd.dependencies.js";
import type { GetSettlementInput, ListSettlementsInput, SettleContestInput } from "@modelescrow/services/settlements";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/contests/{contestId}/settlement
 * Operation: getSettlement
 */
export async function getSettlement(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SettlementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSettlementInput = {
    contestId: request.params.contestId,
  };
  const result = await deps.useCases.settlements.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/contests/{contestId}/settlement
 * Operation: settleContest
 */
export async function settleContest(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SettlementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SettleContestInput = {
    contestId: request.params.contestId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.settlements.update.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/settlements
 * Operation: listSettlements
 */
export async function listSettlements(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SettlementsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSettlementsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.settlements.list.execute(input);
  return reply.code(200).send(result);
}


