/**
 * Invalidate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Invalidate DTOs
 *
 * DDD: Application DTOs for Invalidate use cases.
 */

import type { InvalidateEvaluationRunParams, InvalidateEvaluationRunRequestInput } from "@modelescrow/core/evaluations/types";

export type InvalidateEvaluationRunInput = InvalidateEvaluationRunParams & InvalidateEvaluationRunRequestInput;

export type InvalidateEvaluationRunOutput = {};
