/**
 * SubmissionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmissionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SubmissionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SubmissionRepository,
} from "@modelescrow/services/submissions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SubmissionRepositoryDdb } from "./submission-repository.ddb.js";

/**
 * SubmissionRepositoryAdapter
 *
 * Implements SubmissionRepository port for infrastructure layer.
 */
export class SubmissionRepositoryAdapter implements SubmissionRepository {
  private readonly ddb: SubmissionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SubmissionRepositoryDdb(this.dynamoClient);
  }

  async listSubmissions(input: Parameters<SubmissionRepository['listSubmissions']>[0]): Promise<Awaited<ReturnType<SubmissionRepository['listSubmissions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSubmissions(input);
  }

  async submitModel(input: Parameters<SubmissionRepository['submitModel']>[0]): Promise<Awaited<ReturnType<SubmissionRepository['submitModel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitModel(input);
  }

  async getSubmission(input: Parameters<SubmissionRepository['getSubmission']>[0]): Promise<Awaited<ReturnType<SubmissionRepository['getSubmission']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSubmission(input);
  }

  async withdrawSubmission(input: Parameters<SubmissionRepository['withdrawSubmission']>[0]): Promise<Awaited<ReturnType<SubmissionRepository['withdrawSubmission']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.withdrawSubmission(input);
  }
}
