/**
 * Submission Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/submissions.openapi.types.js";
import { schemas } from "../schemas/submissions.schemas.js";

/**
 * Entity: SubmissionEntity
 * Description: Represents the Submission domain model.
 * Source: schemas.Submission
 * Type: Domain Entity (API)
 */
export const SubmissionEntitySchema = schemas.Submission;
export type SubmissionEntity = components["schemas"]["Submission"];
