/**
 * SubmissionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmissionRepository Port
 *
 * DDD: Application port for submissionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSubmissionInput, GetSubmissionOutput, ListSubmissionsInput, ListSubmissionsOutput, SubmitModelInput, SubmitModelOutput, WithdrawSubmissionInput, WithdrawSubmissionOutput } from "../dto/submission.dto";
export interface SubmissionRepository {
  listSubmissions(input: ListSubmissionsInput): Promise<ListSubmissionsOutput>;
  submitModel(input: SubmitModelInput): Promise<SubmitModelOutput>;
  getSubmission(input: GetSubmissionInput): Promise<GetSubmissionOutput>;
  withdrawSubmission(input: WithdrawSubmissionInput): Promise<WithdrawSubmissionOutput>;
}

export type { GetSubmissionInput, GetSubmissionOutput, ListSubmissionsInput, ListSubmissionsOutput, SubmitModelInput, SubmitModelOutput, WithdrawSubmissionInput, WithdrawSubmissionOutput } from "../dto/submission.dto";
