/**
 * ExecuteSettleContest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSettleContest Use Case
 *
 * DDD: Application use case for update Settlement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SettleContestInput, SettleContestOutput } from "../dto/settlement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { SettlementRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteSettleContest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly settlement: SettlementRepository
  ) {}

  async execute(input: SettleContestInput): Promise<SettleContestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).settlementId) {
      throw new ValidationError("settlementId is required");
    }
    const settlementId = (input as any).settlementId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.settlement.settleContest({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as SettleContestOutput;
  }
}
