/**
 * DeployGate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deploygates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeployGate DTOs
 *
 * DDD: Application DTOs for DeployGate use cases.
 */

import type { CreateDeployGateParams, CreateDeployGateRequestInput, DecideDeployGateParams, DecideDeployGateRequestInput, GetDeployGateParams, ListDeployGatesParams } from "@modelescrow/core/deploygates/types";

export type ListDeployGatesInput = ListDeployGatesParams;

export type CreateDeployGateInput = CreateDeployGateParams & CreateDeployGateRequestInput;

export type GetDeployGateInput = GetDeployGateParams;

export type DecideDeployGateInput = DecideDeployGateParams & DecideDeployGateRequestInput;

export type ListDeployGatesOutput = {};

export type CreateDeployGateOutput = {};

export type GetDeployGateOutput = {};

export type DecideDeployGateOutput = {};
