/**
 * Settlement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Settlement DTOs
 *
 * DDD: Application DTOs for Settlement use cases.
 */

import type { GetSettlementParams, ListSettlementsParams, SettleContestParams, SettleContestRequestInput } from "@modelescrow/core/settlements/types";

export type GetSettlementInput = GetSettlementParams;

export type SettleContestInput = SettleContestParams & SettleContestRequestInput;

export type ListSettlementsInput = ListSettlementsParams;

export type GetSettlementOutput = {};

export type SettleContestOutput = {};

export type ListSettlementsOutput = {};
