/**
 * ContestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ContestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ContestRepository,
} from "@modelescrow/services/contests";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ContestRepositoryDdb } from "./contest-repository.ddb.js";

/**
 * ContestRepositoryAdapter
 *
 * Implements ContestRepository port for infrastructure layer.
 */
export class ContestRepositoryAdapter implements ContestRepository {
  private readonly ddb: ContestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ContestRepositoryDdb(this.dynamoClient);
  }

  async listContests(input: Parameters<ContestRepository['listContests']>[0]): Promise<Awaited<ReturnType<ContestRepository['listContests']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listContests(input);
  }

  async createContest(input: Parameters<ContestRepository['createContest']>[0]): Promise<Awaited<ReturnType<ContestRepository['createContest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createContest(input);
  }

  async getContest(input: Parameters<ContestRepository['getContest']>[0]): Promise<Awaited<ReturnType<ContestRepository['getContest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getContest(input);
  }

  async updateContest(input: Parameters<ContestRepository['updateContest']>[0]): Promise<Awaited<ReturnType<ContestRepository['updateContest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateContest(input);
  }

  async cancelContest(input: Parameters<ContestRepository['cancelContest']>[0]): Promise<Awaited<ReturnType<ContestRepository['cancelContest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.cancelContest(input);
  }
}
