/**
 * Routes for Invalidate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { invalidateEvaluationRun } from "../handlers/invalidate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function invalidateRoutes(fastify: FastifyInstance) {
  // POST /v1/evaluations/{evaluationRunId}/invalidate (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/evaluations/:evaluationRunId/invalidate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { evaluationRunId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvaluationsDependenciesForRequest();
        await invalidateEvaluationRun(request, reply, deps);
      });
    }
  );


}
