/**
 * Routes for Leaderboard
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getLeaderboard } from "../handlers/leaderboard.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function leaderboardRoutes(fastify: FastifyInstance) {
  // GET /v1/contests/{contestId}/leaderboard (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contests/:contestId/leaderboard",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvaluationsDependenciesForRequest();
        await getLeaderboard(request, reply, deps);
      });
    }
  );


}
