/**
 * ExecuteLockEscrow - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escrows
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteLockEscrow Use Case
 *
 * DDD: Application use case for get Escrow.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { LockEscrowInput, LockEscrowOutput } from "../dto/escrow.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { EscrowRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteLockEscrow {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly escrow: EscrowRepository
  ) {}

  async execute(input: LockEscrowInput): Promise<LockEscrowOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.escId();

    // All field names extracted from OpenAPI spec: amount, currency, railReference
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).contestId) {
      throw new ValidationError("contestId is required");
    }
    const contestId = (input as any).contestId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.escrow.lockEscrow({ contestId: contestId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${contestId}`);
    }

    return entity as LockEscrowOutput;
  }
}
