/**
 * SettlementRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlements
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SettlementRepository Port
 *
 * DDD: Application port for settlementrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetSettlementInput, GetSettlementOutput, ListSettlementsInput, ListSettlementsOutput, SettleContestInput, SettleContestOutput } from "../dto/settlement.dto";
export interface SettlementRepository {
  getSettlement(input: GetSettlementInput): Promise<GetSettlementOutput>;
  settleContest(input: SettleContestInput): Promise<SettleContestOutput>;
  listSettlements(input: ListSettlementsInput): Promise<ListSettlementsOutput>;
}

export type { GetSettlementInput, GetSettlementOutput, ListSettlementsInput, ListSettlementsOutput, SettleContestInput, SettleContestOutput } from "../dto/settlement.dto";
