/**
 * InvalidateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InvalidateRepository Port
 *
 * DDD: Application port for invalidaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { InvalidateEvaluationRunInput, InvalidateEvaluationRunOutput } from "../dto/invalidate.dto";
export interface InvalidateRepository {
  invalidateEvaluationRun(input: InvalidateEvaluationRunInput): Promise<InvalidateEvaluationRunOutput>;
}

export type { InvalidateEvaluationRunInput, InvalidateEvaluationRunOutput } from "../dto/invalidate.dto";
