/**
 * LeaderboardRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LeaderboardRepository Port
 *
 * DDD: Application port for leaderboardrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetLeaderboardInput, GetLeaderboardOutput } from "../dto/leaderboard.dto";
export interface LeaderboardRepository {
  getLeaderboard(input: GetLeaderboardInput): Promise<GetLeaderboardOutput>;
}

export type { GetLeaderboardInput, GetLeaderboardOutput } from "../dto/leaderboard.dto";
