/**
 * Repository interface for Contest
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ContestEntity
} from "../models/contest.entity.js";
import type {
  ListContestsParams,
  Contest,
  UpdateContestRequestInput
} from "../types/index.js";
/**
 * ContestRepository Interface
 */
export interface ContestRepository extends CreateUpdateReadRepository<ContestEntity, Contest, UpdateContestRequestInput, string, ListContestsParams> {

}
