/**
 * DisputeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisputeRepository Port
 *
 * DDD: Application port for disputerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDisputeInput, GetDisputeOutput, ListDisputesInput, ListDisputesOutput, OpenEvaluationDisputeInput, OpenEvaluationDisputeOutput, ResolveDisputeInput, ResolveDisputeOutput } from "../dto/dispute.dto";
export interface DisputeRepository {
  listDisputes(input: ListDisputesInput): Promise<ListDisputesOutput>;
  openEvaluationDispute(input: OpenEvaluationDisputeInput): Promise<OpenEvaluationDisputeOutput>;
  getDispute(input: GetDisputeInput): Promise<GetDisputeOutput>;
  resolveDispute(input: ResolveDisputeInput): Promise<ResolveDisputeOutput>;
}

export type { GetDisputeInput, GetDisputeOutput, ListDisputesInput, ListDisputesOutput, OpenEvaluationDisputeInput, OpenEvaluationDisputeOutput, ResolveDisputeInput, ResolveDisputeOutput } from "../dto/dispute.dto";
