/**
 * Escrows DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escrows
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Escrows Domain Module - Composition root
 *
 * DDD: Composition root for escrows domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EscrowRepositoryAdapter,
} from "@modelescrow/adapters/escrows";
import { getIdGeneratorService } from "@modelescrow/adapters";
import type { AdapterDynamoDBClient } from "@modelescrow/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetEscrow,
  ExecuteGetEscrowById,
  ExecuteLockEscrow,
} from "@modelescrow/services/escrows/usecases";
// Ports (interfaces)
import type {
  EscrowRepository,
} from "@modelescrow/services/escrows/ports";

export interface EscrowsDomainModule {
  repos: {
    escrows: EscrowRepository;
  };
  useCases: {
    escrows: {
      get: ExecuteLockEscrow;
      getById: ExecuteGetEscrowById;
    };
  };
}

export function buildEscrowsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EscrowsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      escrows?: EscrowRepository;
    } = {};

    obj.escrows = new EscrowRepositoryAdapter(dynamoClient);
    return {
      escrows: obj.escrows!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    escrows: {
      get: new ExecuteLockEscrow(executionContext, idGenerator, repos.escrows),
      getById: new ExecuteGetEscrowById(executionContext, idGenerator, repos.escrows),
    },
  };
  return { repos, useCases: useCases as EscrowsDomainModule["useCases"] };
}
