/**
 * Escrow DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escrows
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Escrow DTOs
 *
 * DDD: Application DTOs for Escrow use cases.
 */

import type { GetEscrowByIdParams, GetEscrowParams, LockEscrowParams, LockEscrowRequestInput } from "@modelescrow/core/escrows/types";

export type GetEscrowInput = GetEscrowParams;

export type LockEscrowInput = LockEscrowParams & LockEscrowRequestInput;

export type GetEscrowByIdInput = GetEscrowByIdParams;

export type GetEscrowOutput = {};

export type LockEscrowOutput = {};

export type GetEscrowByIdOutput = {};
