/**
 * Handlers for Submission
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SubmissionsDomainModule } from "../dependencies/submissions-ddd.dependencies.js";
import type { GetSubmissionInput, ListSubmissionsInput, SubmitModelInput, WithdrawSubmissionInput } from "@modelescrow/services/submissions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/contests/{contestId}/submissions
 * Operation: listSubmissions
 */
export async function listSubmissions(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSubmissionsInput = {
    contestId: request.params.contestId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.submissions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/contests/{contestId}/submissions
 * Operation: submitModel
 */
export async function submitModel(
  request: FastifyRequest<{ Params: { contestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitModelInput = {
    contestId: request.params.contestId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.submissions.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/submissions/{submissionId}
 * Operation: getSubmission
 */
export async function getSubmission(
  request: FastifyRequest<{ Params: { submissionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSubmissionInput = {
    submissionId: request.params.submissionId,
  };
  const result = await deps.useCases.submissions.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for DELETE /v1/submissions/{submissionId}
 * Operation: withdrawSubmission
 */
export async function withdrawSubmission(
  request: FastifyRequest<{ Params: { submissionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: WithdrawSubmissionInput = {
    submissionId: request.params.submissionId,
  };
  const result = await deps.useCases.submissions.get.execute(input);
  return reply.code(204).send(result);
}


