/**
 * ExecuteUpdateContest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateContest Use Case
 *
 * DDD: Application use case for update Contest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateContestInput, UpdateContestOutput } from "../dto/contest.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { ContestRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateContest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contest: ContestRepository
  ) {}

  async execute(input: UpdateContestInput): Promise<UpdateContestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cntId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).contestId) {
      throw new ValidationError("contestId is required");
    }
    const contestId = (input as any).contestId;

    // Load existing entity
    const existing = await this.contest.getContest({ contestId: contestId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${contestId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.contest.updateContest({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateContestOutput;
  }
}
