/**
 * ExecuteCreateContest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateContest Use Case
 *
 * DDD: Application use case for create Contest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateContestInput, CreateContestOutput } from "../dto/contest.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { ContestRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateContest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contest: ContestRepository
  ) {}

  async execute(input: CreateContestInput): Promise<CreateContestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cntId();

    // All field names extracted from OpenAPI spec: acceptanceThreshold, datasetHash, datasetId, deadline, evaluationFunction, leaderboardVisibility, metricName, requireHumanDeployGate, rewardAmount, rewardCurrency, sealedEvaluation, takeRate, title
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.datasetHash) {
      throw new ValidationError("datasetHash is required");
    }
    if (!input.deadline) {
      throw new ValidationError("deadline is required");
    }
    if (!input.evaluationFunction) {
      throw new ValidationError("evaluationFunction is required");
    }
    if (!input.title) {
      throw new ValidationError("title is required");
    }
    if (!input.rewardAmount) {
      throw new ValidationError("rewardAmount is required");
    }
    if (!input.metricName) {
      throw new ValidationError("metricName is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (contests domain)
    const entityId = this.idGenerator.cntId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.contest.createContest({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateContestOutput;
  }
}
