/**
 * ExecuteGetContest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetContest Use Case
 *
 * DDD: Application use case for get Contest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetContestInput, GetContestOutput } from "../dto/contest.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { ContestRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetContest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contest: ContestRepository
  ) {}

  async execute(input: GetContestInput): Promise<GetContestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cntId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).contestId) {
      throw new ValidationError("contestId is required");
    }
    const contestId = (input as any).contestId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.contest.getContest({ contestId: contestId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${contestId}`);
    }

    return entity as GetContestOutput;
  }
}
