/**
 * ExecuteListContests - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contests
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListContests Use Case
 *
 * DDD: Application use case for list Contest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListContestsInput, ListContestsOutput } from "../dto/contest.dto";
import type { ExecutionContextService, IdGeneratorService } from "@modelescrow/services/_shared/index.js";
import type { ContestRepository } from "../ports";

export class ExecuteListContests {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contest: ContestRepository
  ) {}

  async execute(input: ListContestsInput): Promise<ListContestsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cntId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.contest.listContests({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListContestsOutput;
  }
}
